services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: minimal10digittransformer:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
